import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ weight: "400", subsets: ["latin"]});
const keepCalm = localFont({
    src: [
        {
            path: '../public/fonts/KeepCalm-Medium.ttf',
            weight: '400'
        },
    ],
    variable: '--font-keepcalm'
})

export const metadata: Metadata = {
  title: "Start your Ascension",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${keepCalm.variable} ${roboto.className}`}>
      <Header/>
      <main>{children}</main>
      <Footer/>
      </body>
    </html>
  );
}
