import type { Metadata } from "next";
import {Inter, Roboto, Roboto_Condensed} from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import Toaster from "@/components/ui/toaster"


const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ weight: ["400","700"], subsets: ["latin"]});
const keepCalm = localFont({
    src: [
        {
            path: '../public/fonts/KeepCalm-Medium.ttf',
            weight: '400'
        },
    ],
    variable: '--font-keepcalm'
})
const robotoCondensed = Roboto_Condensed({ weight: "400", subsets: ["latin"]})

export const metadata: Metadata = {
  title: "Start your Ascension",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${keepCalm.variable} ${roboto.className} ${robotoCondensed.className}`}>
      <div className={"min-h-[100vh] flex flex-col"}>
          <Header/>
          <Toaster/>
          {children}
          <Footer/>
      </div>
      </body>
    </html>
  );
}
